GET http://localhost:8082/users

###

GET http://localhost:8082/users/15

###

POST http://localhost:8082/users/
Content-Type: application/json

{
    'first_name': "John",
    'last_name': "Smith",
    'username: "jsmith",
    'password': "12345"

}